site_name: My awesome documentation on railway
theme:
  name: material
  palette:
    scheme: slate
    primary: teal
  features:
    - navigation.instant
    - navigation.expand
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
