[build]
buildCommand = "mkdocs build"

[deploy]
numReplicas = 1
startCommand = "python -m http.server 8000 --directory site/"
sleepApplication = false
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10